In [3]:
import numpy as np
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)
A

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 1.],
        [0., 1., 0., 0.],
        [1., 0., 1., 0.]])

In [4]:
X = np.matrix([
    [i, -i]
    for i in range(A.shape[0])
], dtype=float)
X

matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [5]:
A*X

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

In [6]:
I = np.matrix(np.eye(A.shape[0]))
(A+I)*X

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [13]:
D = np.array(np.sum(A, axis=0))[0]
D = np.matrix(np.diag(D))
D

matrix([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 1.]])

In [17]:
temp = D**-1 * A
temp

matrix([[0. , 1. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0. , 0.5, 0. , 0. ],
        [1. , 0. , 1. , 0. ]])

In [18]:
temp*X

matrix([[ 1. , -1. ],
        [ 2.5, -2.5],
        [ 0.5, -0.5],
        [ 2. , -2. ]])

In [7]:
import numpy as np
from networkx import karate_club_graph, to_numpy_matrix

In [4]:
zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))

In [5]:
A = to_numpy_matrix(zkc, nodelist=order)

In [8]:
I = np.eye(zkc.number_of_nodes())

In [9]:
A_hat = A + I

In [10]:
D_hat = np.array(np.sum(A_hat, axis=0))[0]

In [11]:
D_hat = np.matrix(np.diag(D_hat))

In [12]:
W_1 = np.random.normal(loc=0, scale=1, size=(zkc.number_of_nodes(), 4))
W_2 = np.random.normal(loc=0, size=(W_1.shape[1], 2))

In [19]:
def relu(x):
    x[x<0]=0
    return x

In [20]:
def gcn_layer(A_hat, D_hat, X, W):
    return relu(D_hat**-1 * A_hat * X * W)

In [21]:
H_1 = gcn_layer(A_hat, D_hat, I, W_1)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)

In [29]:
output = H_2
output

matrix([[0.70610776, 0.03757378],
        [1.21846254, 0.08680767],
        [0.52050872, 0.04292017],
        [0.56648745, 0.03310858],
        [0.08267323, 0.        ],
        [0.17362556, 0.        ],
        [0.20416611, 0.        ],
        [0.35418374, 0.0132185 ],
        [0.72919573, 0.05844857],
        [0.64187219, 0.11421444],
        [0.1862992 , 0.        ],
        [0.05989521, 0.        ],
        [0.27057349, 0.00610344],
        [0.66582249, 0.06531835],
        [0.6421983 , 0.06086155],
        [0.97614009, 0.12520662],
        [0.23816113, 0.        ],
        [0.43269644, 0.01433232],
        [0.60834989, 0.10588754],
        [0.80502456, 0.08989313],
        [1.08006346, 0.15025226],
        [1.28109119, 0.08141837],
        [0.32255866, 0.02714614],
        [0.70419555, 0.13825174],
        [1.19539709, 0.12698184],
        [1.25933357, 0.15664868],
        [1.10626491, 0.25498247],
        [1.03092621, 0.14334033],
        [0.84840316, 0.097076  ],
        [0.922

In [28]:
feature_representations = {
    node: np.array(output)[node] 
    for node in zkc.nodes()}
feature_representations

{0: array([0.70610776, 0.03757378]),
 1: array([1.21846254, 0.08680767]),
 2: array([0.52050872, 0.04292017]),
 3: array([0.56648745, 0.03310858]),
 4: array([0.08267323, 0.        ]),
 5: array([0.17362556, 0.        ]),
 6: array([0.20416611, 0.        ]),
 7: array([0.35418374, 0.0132185 ]),
 8: array([0.72919573, 0.05844857]),
 9: array([0.64187219, 0.11421444]),
 10: array([0.1862992, 0.       ]),
 11: array([0.05989521, 0.        ]),
 12: array([0.27057349, 0.00610344]),
 13: array([0.66582249, 0.06531835]),
 14: array([0.6421983 , 0.06086155]),
 15: array([0.97614009, 0.12520662]),
 16: array([0.23816113, 0.        ]),
 17: array([0.43269644, 0.01433232]),
 18: array([0.60834989, 0.10588754]),
 19: array([0.80502456, 0.08989313]),
 20: array([1.08006346, 0.15025226]),
 21: array([1.28109119, 0.08141837]),
 22: array([0.32255866, 0.02714614]),
 23: array([0.70419555, 0.13825174]),
 24: array([1.19539709, 0.12698184]),
 25: array([1.25933357, 0.15664868]),
 26: array([1.10626491, 